ResumeProject/urls.py
from django.contrib import admin
from django.urls import path,include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view),
    path('services/', include('services.urls')),
    path('skills/', include('skills.urls')),
    path('contacts/', include('contact.urls')),
]

contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('contact/', views.contact_view),
]

services/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('service/', views.services_view),
]

skills/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('skill/', views.skill_view),
]

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

services/models.py
from django.db import models

# Create your models here.

skills/models.py
from django.db import models

# Create your models here.

contact/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField

my_default_errors = {
    'required': 'This field is required',
    'invalid': 'Enter a valid phone number (e.g. +918888888888).'
}

class ContactForm(forms.Form):
    name = forms.CharField(max_length=50)
    com_name = forms.CharField(max_length=60)
    com_add = forms.CharField(max_length=100)
    email = forms.EmailField()
    mobile = PhoneNumberField(error_messages=my_default_errors)
    message = forms.CharField(widget=forms.Textarea)

contact/views.py
from django.shortcuts import render
from .forms import ContactForm
from django.shortcuts import redirect
from ResumeProject import settings
from django.core.mail import send_mail
from django.contrib import messages


# Create your views here.
def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            com_name = form.cleaned_data['com_name']
            com_add = form.cleaned_data['com_add']
            email = form.cleaned_data['email']
            mobile = form.cleaned_data['mobile']
            message = form.cleaned_data['message']
            all_data = f"Name: {name}\nCompany Name: {com_name}\nCompany Address: {com_add}\nEmail: {email}\nMobile: {mobile}\nMessage: {message}"
            subject = "Message from my resume site"
            sender = 'beyondhorrizon7@gmail.com'
            recipients = ['akashmothe1@gmail.com']

            sent = send_mail(subject, all_data, sender, recipients,fail_silently=False,auth_user=settings.EMAIL_HOST_USER,auth_password=settings.EMAIL_HOST_PASSWORD)
            if sent == 1:
                messages.success(request,'Success, Your message has been sent successfully. Thanks for contacting me, I will be shortly in touch with you.')
                return redirect('/')
            else:
                messages.error(request,'Sending Failed, Something went wrong please try again once.')
                return redirect('/')
    else:
        form = ContactForm()
    return render(request,'contact/contact.html',{'contact':'active','form':form})

home/views.py
from django.shortcuts import render

# Create your views here.
def home_view(request):
    return render(request,'home/index.html',{'home':'active'})

services/views.py
from django.shortcuts import render

# Create your views here.
def services_view(request):
    return render(request,'services/services.html',{'services':'active'})

skills/views.py
from django.shortcuts import render

# Create your views here.
def skill_view(request):
    return render(request,'skills/skills.html',{'skills':'active'})

templates/contact/contact.html
<!DOCTYPE html>
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<section id="contact">
    <h1 class="heading">CONTACT</h1>
    <p class="head-p">Do you have any questions? Please do not hesitate to contact. I will come back to you
        within a matter of hours to help you.</p>
    <div class="contact">
        <form action="" method="post" id="form-wrapper">
            {% csrf_token %}
            {{form.non_field_errors}}
            <div class="field">
                {{form.name.errors}}
                <label for="id_name">Name: </label>
                {{form.name}}
                <!-- <input type="text" id="name" name="name"> -->
            </div>
            <div class="field">
                {{form.com_name.errors}}
                <label for="id_com_name">Compnay Name: </label>
                {{form.com_name}}
                <!-- <input type="text" id="com-name" name="com_name"> -->
            </div>
            <div class="field">
                {{form.com_add.errors}}
                <label for="id_com_add">Company Address: </label>
                {{form.com_add}}
                <!-- <input type="text" id="com-add" name="com_add"> -->
            </div>
            <div class="field">
                {{form.email.errors}}
                <label for="id_email">Your Email: </label>
                {{form.email}}
                <!-- <input type="text" id="email" name="email"> -->
            </div>
            <div class="field">
                {{form.mobile.errors}}
                <label for="id_mobile">Mobile No.: </label>
                {{form.mobile}}
                <!-- <input type="text" id="mobile" name="mobile"> -->
            </div>
            <div class="field">
                {{form.message.errors}}
                <label for="id_message">Message: </label>
                {{form.message}}
                <!-- <input type="text" id="message" name="message"> -->
            </div>
            <div class="form-btn">
                <input type="submit" value="Send">
            </div>
        </form>
        <div class="details-box">
            <div class="box">
                <i class="fas fa-map-marker-alt"></i>
                <p>Mehkar,Maharastra,India</p>
            </div>
            <div class="box">
                <i class="fas fa-phone-alt"></i>
                <p>+91-9921542442</p>
            </div>
            <div class="box">
                <i class="fas fa-envelope"></i>
                <p>motheakash321@gmail.com</p>
            </div>
            <div class="social-links">
                <a href="https://twitter.com/AkashMothe"><i class="fab fa-twitter"></i></a>
                <a href="https://www.facebook.com/akash.mothe.967"><i class="fab fa-facebook"></i></a>
                <a href="https://www.instagram.com/mr.akk1/?hl=en"><i class="fab fa-instagram"></i></a>
                <a href="https://in.linkedin.com/"><i class="fab fa-linkedin"></i></a>
                
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/home/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/resume_style.css' %}">
    <script src="https://kit.fontawesome.com/b71f055dc5.js" crossorigin="anonymous"></script>

    <title>My Resume</title>
</head>

<body>
    {% for message in messages%}
    <div class="alert my-alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>Message: </strong> {{message}}
        <button type="button" href="/" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {%endfor%}
    <div class="container-fluid">
        <div class="nav-column">
            <div class="img-box">
                <img src="{% static 'images/akash-dp.jpg' %}" class="rounded-circle" alt="Profile">
                <h2 class="name">Akash Mothe</h2>
            </div>
            <div class="img-box-line"></div>
            <div class="nav-links">
                <ul>
                    <li class="{{home}}"><a href="/">Home</a></li>
                    <li class="{{services}}"><a href="/services/service">Services</a></li>
                    <li class="{{skills}}"><a href="/skills/skill">Skills</a></li>
                    <li class="{{contact}}"><a href="/contacts/contact">Contact Me</a></li>
                </ul>
            </div>
        </div>
        {% block content %}
        
        {% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="{% static 'js/base.js' %}"></script> -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>

</html>

templates/home/index.html
<!DOCTYPE html>
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<section id="home-content">
    <img src="{% static 'images/akash-pot.jpg' %}" alt="Profile">
    <h1 class="hello">Hello,</h1>
    <p class="profile-para">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        I am <span>Akash Mothe</span> having 5 years of full-stack web development experience for global
        businesses, I offer the technical expertise you are seeking for your web developer position. <br><br>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere veritatis illum qui nesciunt modi
        voluptates omnis quae nihil maxime quaerat mollitia doloremque totam dolorum veniam accusantium laborum
        molestiae quod sunt maiores quisquam non, tempora at amet. Accusantium atque doloribus accusamus? Lorem
        ipsum dolor sit amet consectetur adipisicing elit. Iusto ex fugit veritatis ducimus placeat tempore
        blanditiis sint minima doloribus minus, laborum tempora in assumenda odio eveniet corrupti culpa
        commodi? Pariatur esse natus eius exercitationem quas eligendi commodi corporis rerum doloribus.
        <br><br> Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere veritatis illum qui nesciunt
        modi voluptates omnis quae nihil maxime quaerat mollitia doloremque totam dolorum veniam accusantium
        laborum molestiae quod sunt maiores quisquam non, tempora at amet. Accusantium atque doloribus
        accusamus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto ex fugit veritatis ducimus
        placeat tempore blanditiis sint minima doloribus minus, laborum tempora in assumenda odio eveniet
        corrupti culpa commodi? Pariatur esse natus eius exercitationem quas eligendi commodi corporis rerum
        doloribus. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ea, mollitia!</p>
    <div class="bottom-btns">
        <a href="/contacts/contact" class="bottom-btn hire-me">Hire Me</a>
        <a href="https://github.com/SkyCoder-ak" class="bottom-btn my-projects">My Projects</a>
    </div>
</section>
{% endblock content %}

templates/services/services.html
<!DOCTYPE html>
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<section id="services">
    <h1 class="heading">SERVICES</h1>
    <div class="service-row">
        <div class="service-box">
            <i class="fas fa-code fa-2x mb-3 i-color"></i>
            <h3>Web Development</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus, numquam.</p>
        </div>
        <div class="service-box">
            <i class="fas fa-palette"></i>
            <h3>Web Design</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus, numquam.</p>
        </div>
        <div class="service-box">
            <i class="fas fa-server"></i>
            <h3>Backend Coding</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus, numquam.</p>
        </div>
    </div>
    <div class="service-row">
        <div class="service-box">
            <i class="fas fa-database"></i>
            <h3>Database Management</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus, numquam.</p>
        </div>
        <div class="service-box">
            <i class="fas fa-keyboard"></i>
            <h3>Freelancing</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus, numquam.</p>
        </div>
        <div class="service-box">
            <i class="fas fa-desktop"></i>
            <h3>System Software Development</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus, numquam.</p>
        </div>
    </div>
    <div class="service-row">
        <div class="service-box">
            <i class="fas fa-headset fa-2x mb-3 i-color"></i>
            <h3>Supports</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus, numquam.</p>
        </div>
        <div class="service-box">
            <i class="fas fa-ad fa-2x mb-3 i-color"></i>
            <h3>Advertising</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus, numquam.</p>
        </div>
        <div class="service-box">
            <i class="fab fa-xbox"></i>
            <h3>Game Development</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus, numquam.</p>
        </div>
    </div>
</section>
{% endblock content %}

templates/skills/skills.html
<!DOCTYPE html>
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<section id="skills">
    <h1 class="heading">SKILLS</h1>
    <div class="skill-row">
        <div class="skill-col">
            <h3>Python</h3>
            <div class="outer-bar">
                <div class="python"><span>95%</span></div>
            </div>
        </div>
        <div class="skill-col">
            <h3>HTML/CSS</h3>
            <div class="outer-bar">
                <div class="html-css"><span>90%</span></div>
            </div>
        </div>
    </div>

    <div class="skill-row">
        <div class="skill-col">
            <h3>JavaScript</h3>
            <div class="outer-bar">
                <div class="javascript"><span>80%</span></div>
            </div>
        </div>
        <div class="skill-col">
            <h3>Django</h3>
            <div class="outer-bar">
                <div class="jango"><span>90%</span></div>
            </div>
        </div>
    </div>

    <div class="skill-row">
        <div class="skill-col">
            <h3>Machine Learning</h3>
            <div class="outer-bar">
                <div class="machine-learning"><span>60%</span></div>
            </div>
        </div>
        <div class="skill-col">
            <h3>Deep Learning</h3>
            <div class="outer-bar">
                <div class="deep-learning"><span>50%</span></div>
            </div>
        </div>
    </div>

    <div class="skill-row">
        <div class="skill-col">
            <h3>Java</h3>
            <div class="outer-bar">
                <div class="java"><span>60%</span></div>
            </div>
        </div>
        <div class="skill-col">
            <h3>C++</h3>
            <div class="outer-bar">
                <div class="c-plus"><span>65%</span></div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}